
import { app, BrowserWindow } from 'electron';
import path from 'path';
import setUpHandlers from './handlers';

// This constant is generated by Electron Forge's Vite plugin
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

const isDev = process.env.NODE_ENV === 'development';

const preloadPath = isDev
  ? path.join(app.getAppPath(), '.vite/preload/index.js')
  : path.join(__dirname, '..', 'preload', 'index.js');

const createWindow = () => {
  const mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      // Points to the bundled preload script
      preload: preloadPath,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  // If we are in development, load the Vite server
  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
  } else {
    // In production, load the bundled html file
    mainWindow.loadFile(path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`));
  }

  // Open DevTools in development
  if (process.env.NODE_ENV === 'development') {
    mainWindow.webContents.openDevTools();
  }
};

app.on('ready', () => {
  createWindow();
  setUpHandlers();
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});



